name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.epicheads.EpicHeads
softdepend:
  - PlayerPoints
  - Reserve
  - Vault

author: Songoda
website: ${project.url}

commands:
  EpicHeads:
    description: View information on this plugin.
    default: true
    aliases: [ heads, ehe ]
    usage: /epicheads
